channels:
- conda-forge
dependencies:
- python=3.10.2
- pip<=24.3.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.25.2
  - pandas==2.1.3
  - psutil==5.9.8
  - scikit-learn==1.3.1
  - scipy==1.11.3
name: mlflow-env
